name: Cross Info Update

on:
  push:
    branches:
      - main
    paths:
      - 'src/components/namecross/workers.json'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::crossword.r
            any::jsonlite

      - name: Check out repository
        uses: actions/checkout@v3

      - name: update cross info
        run: Rscript cross.r

      - name: commit by Github Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update cross info"
            git pull origin ${{ github.ref }} --rebase
            git push origin ${{ github.ref }}
            gh workflow run deploy.yml
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
